Add option to pass progress callback
idrsolutions/idrsolutions-php-client pull request #8
Opened 2023-03-06 10:45 UTC by dvahram

2023-03-31 13:21 UTC, daniel-warren requested changes
Suggesting minor code-style changes to match the existing style, but otherwise I'm happy with the proposed changes 👍

2023-03-31 13:23 UTC, daniel-warren commented on src/IDRCloudClient.php
> +            isset($opt[self::KEY_PROGRESS_CALLBACK]) ? $opt[self::KEY_PROGRESS_CALLBACK] : null
```suggestion
            (array_key_exists(self::KEY_PROGRESS_CALLBACK, $opt)) ? $opt[self::KEY_PROGRESS_CALLBACK] : null
```
(Not sure how this suggestion didn't get included with the review, but adding now)

2023-03-31 14:29 UTC, dvahram commented
@daniel-warren I've addressed your code style suggestions. Please take a look. Please let me know if there is anything else.

2023-03-31 14:30 UTC, daniel-warren approved these changes
Looks good!

2023-04-03 09:08 UTC, josrepo approved these changes

2023-04-06 11:05 UTC, KieranFrance approved these changes

2023-04-06 11:06 UTC, merged